export const selectCars = state => state.cars.items;
export const selectIsLoading = state => state.cars.isLoading;
export const selectError = state => state.cars.error;
export const selectFavorites = state => state.cars.favorites;
export const selectTotalPages = state => state.cars.totalPages;
export const selectPage = state => state.cars.page;
export const selectTotalCars = state => state.cars.totalCars;
export const selectHasMore = state => state.cars.hasMore;
export const selectSelectedCar = state => state.cars.selectedCar;
